### ISSUE TITLE
Error in log file

### ISSUE THREAD

**Issue by Tsyklop** [shadowfacts/ShadowTweaks#2]
http://pastebin.com/jAUpGkty

ShadowTweaks-1.7.10-1.5.0

**Comment by shadowfacts** [comment]
~~Did you enable `sleepWhenRaining` in the config file?~~

Nevermind, that wouldn't affect the transformer.

**Comment by Tsyklop** [comment]
can you fix this?

**Comment by shadowfacts** [comment]
This has been fixed, I just need to push a new build.

**Comment by shadowfacts** [comment]
1.5.1 is pending approval on Curse.
